include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    todo: ignore

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - avoid_unused_constructor_parameters
    - directives_ordering
    - prefer_const_constructors
    - prefer_final_locals
    - prefer_relative_imports
    - public_member_api_docs
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - unawaited_futures
    - use_super_parameters
